[package]
name = "vgtk"
version = "0.2.1"
authors = ["Bodil Stokke <bodil@bodil.org>"]
edition = "2018"
license = "LGPL-3.0+"
description = "A declarative UI framework for GTK"
repository = "https://github.com/bodil/vgtk"
documentation = "https://docs.rs/vgtk"
homepage = "http://vgtk.rs"
readme = "../README.md"
categories = ["gui"]
keywords = ["gtk"]

[dependencies]
gio = "0.8.1"
glib = "0.9.3"
gdk = "0.12.1"
gdk-pixbuf = "0.8.0"
vgtk-macros = { path = '../macros' }
proc-macro-hack = "0.5.10"
proc-macro-nested = "0.1.3"
log = "0.4.8"
colored = "1.8.0"
futures = "0.3.0"

[dependencies.gtk]
version = "0.8.1"
features = ["embed-lgpl-docs", "v3_24"]
